services:
  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db:
        conditon: service_healthy
    environment:
      PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8080"
  
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  swagger:
    image: swaggerapi/swagger-ui:latest
    restart: unless-stopped
    environment:
      SWAGGER_JSON: /openapi.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro

volumes:
  pgdata:
